### ISSUE TITLE
Crash on enable true north setting

### ISSUE THREAD

**Issue by ChemicalXandco** [Kr0oked/Compass#39]
When enabling the true north setting, the app will crash and will crash immediately on every subsequent start.

Logcat output:

```
05-06 12:24:50.394  3791  3791 E AndroidRuntime: FATAL EXCEPTION: main
05-06 12:24:50.394  3791  3791 E AndroidRuntime: Process: com.bobek.compass, PID: 3791
05-06 12:24:50.394  3791  3791 E AndroidRuntime: java.lang.RuntimeException: Unable to resume activity {com.bobek.compass/com.bobek.compass.MainActivity}: java.lang.IllegalArgumentException: provider doesn't exist: network
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4438)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7664)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: provider doesn't exist: network
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2378)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2358)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2341)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2283)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:1297)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1178)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1139)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:931)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at com.bobek.compass.CompassFragment.D(SourceFile:137)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at androidx.fragment.app.t0.n(SourceFile:113)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at androidx.fragment.app.t0.k(SourceFile:45)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at androidx.fragment.app.n0.O(SourceFile:63)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at androidx.fragment.app.n0.u(SourceFile:36)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at androidx.fragment.app.t0.n(SourceFile:146)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at androidx.fragment.app.t0.k(SourceFile:45)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at androidx.fragment.app.n0.O(SourceFile:63)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at androidx.fragment.app.n0.u(SourceFile:36)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at androidx.fragment.app.x.onPostResume(SourceFile:29)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at d.q.onPostResume(SourceFile:1)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:8154)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4428)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	... 11 more
05-06 12:24:50.394  3791  3791 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at com.android.server.location.LocationManagerService.requestLocationUpdatesLocked(LocationManagerService.java:1964)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at com.android.server.location.LocationManagerService.requestLocationUpdates(LocationManagerService.java:1947)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:540)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
05-06 12:24:50.394  3791  3791 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:1123)
```

System details:
LineageOS 18.1
Android 11

**Comment by Kr0oked** [comment]
Thanks for reporting this bug. For now you can reinstall the app, which should reset your app settings. So the app starts without the true north feature enabled and you can use it again.
This bug occurres when your system does not provide the network location provider. I will fix it by querying for the best fitting provider that a system can provide and use it instead. If no provider can be used I will show an error message and the compass can still be used without the true north feature.
I will release a new app version with the bug fix as soon as possible.
